# Generated by Django 4.2.5 on 2023-09-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_token_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expired',
            field=models.DateTimeField(),
        ),
    ]
