# Generated by Django 4.2.5 on 2023-09-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_token_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='otp',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='otp_expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
