# Generated by Django 4.2.5 on 2023-09-30 22:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0007_alter_token_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='ip_address',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together={('user', 'ip_address')},
        ),
    ]
