# Generated by Django 4.2.5 on 2023-10-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_token_ip_address_alter_token_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='otp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
